name: BatchHook
options:
  bundleIdPrefix: com.shimondeitel.rughookinglog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "5"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  BatchHook:
    type: application
    platform: iOS
    sources:
      - path: BatchHook
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.rughookinglog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: BatchHook/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  BatchHookTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BatchHookTests
      - path: BatchHook.storekit
    dependencies:
      - target: BatchHook
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.rughookinglog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  BatchHookUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: BatchHookUITests
    dependencies:
      - target: BatchHook
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.rughookinglog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  BatchHook:
    build:
      targets:
        BatchHook: all
        BatchHookTests: [test]
        BatchHookUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: BatchHook.storekit
    test:
      config: Debug
      storeKitConfiguration: BatchHook.storekit
      targets:
        - BatchHookTests
        - BatchHookUITests
    archive:
      config: Release
